#!/usr/bin/env bash
# Vendor the Umberleaf brand mark into this repo.
#
# The generator lives deliberately OUTSIDE every repo, at ~/projects/umberleaf-brand
# (override with UMBERLEAF_BRAND). This script only COPIES what that generator
# emitted; it never redraws the mark. The platform repo has the same script as
# `scripts/brand/sync.mjs`, so one mark reaches three repos by copy, not by redraw.
#
#   python3 ~/projects/umberleaf-brand/generate_outline.py   # redraw (rare)
#   tool/branding/sync.sh                                    # vendor here
#   tool/branding/sync.sh --check                            # verify only, non-zero on drift
#   dart run flutter_launcher_icons                          # rasterize launcher icons
#
# Why a sync script and not a generator in-repo: the previous mark was generated by
# `tool/branding/generate_glyph.py`, which rendered the Arabic qaf from a system
# font. That file is gone — left in place it would happily regenerate the OLD mark
# over the new one, months from now, with a green build.
set -euo pipefail

BRAND="${UMBERLEAF_BRAND:-$HOME/projects/umberleaf-brand}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

if [[ ! -d "$BRAND" ]]; then
  echo "brand generator not found at $BRAND — set UMBERLEAF_BRAND" >&2
  exit 2
fi

# source-in-brand-repo  ->  destination-in-this-repo
declare -a PAIRS=(
  "png/umberleaf_1024.png|assets/branding/umberleaf_icon.png"
  "png/umberleaf_fg_1024.png|assets/branding/umberleaf_icon_foreground.png"
  "umberleaf_icon.svg|assets/branding/umberleaf_icon.svg"
  "umberleaf_glyph_path.dart|lib/shared/widgets/branding/umberleaf_glyph_path.dart"
)

drift=0
for pair in "${PAIRS[@]}"; do
  src="$BRAND/${pair%%|*}"
  dst="$REPO/${pair##*|}"
  if [[ ! -f "$src" ]]; then
    echo "MISSING SOURCE: $src — re-run generate_outline.py" >&2
    exit 2
  fi
  if [[ "$CHECK" == 1 ]]; then
    if ! cmp -s "$src" "$dst"; then
      echo "DRIFT: ${pair##*|} differs from the generated master"
      drift=$((drift + 1))
    fi
  else
    cp "$src" "$dst"
    echo "wrote ${pair##*|}"
  fi
done

if [[ "$CHECK" == 1 ]]; then
  if [[ "$drift" == 0 ]]; then
    echo "brand assets in sync"
  else
    echo "$drift file(s) drifted — run tool/branding/sync.sh"
    exit 1
  fi
else
  echo
  echo "Launcher icons are NOT regenerated by this script. Run:"
  echo "  dart run flutter_launcher_icons"
fi
